output: group
tasks:
  _deploydeps:
    deps:
    - deploy_component_external_dns
    - deploy_component_nginx_ingress
    - deploy_component_pharos
    - deploy_component_sealed_secrets
  _gendeps:
    deps:
    - generate_component_external_dns
    - generate_component_nginx_ingress
    - generate_component_pharos
    - generate_component_sealed_secrets
  _rundeps:
    deps:
    - dryrun_component_external_dns
    - dryrun_component_nginx_ingress
    - dryrun_component_pharos
    - dryrun_component_sealed_secrets
  deploy:
    cmds:
    - task: _deploydeps
  deploy_component_external_dns:
    cmds:
    - bin/deployer validate prod2 external_dns
    - bin/deployer update prod2 external_dns
    desc: deploy  external_dns for prod2
    dir: $KR8_BASE/
    status:
    - bin/deployer diff prod2 external_dns
  deploy_component_nginx_ingress:
    cmds:
    - bin/deployer validate prod2 nginx_ingress
    - bin/deployer update prod2 nginx_ingress
    desc: deploy  nginx_ingress for prod2
    dir: $KR8_BASE/
    status:
    - bin/deployer diff prod2 nginx_ingress
  deploy_component_pharos:
    cmds:
    - bin/deployer validate prod2 pharos
    - bin/deployer update prod2 pharos
    desc: deploy  pharos for prod2
    dir: $KR8_BASE/
    status:
    - bin/deployer diff prod2 pharos
  deploy_component_sealed_secrets:
    cmds:
    - bin/deployer validate prod2 sealed_secrets
    - bin/deployer update prod2 sealed_secrets
    desc: deploy  sealed_secrets for prod2
    dir: $KR8_BASE/
    status:
    - bin/deployer diff prod2 sealed_secrets
  dryrun:
    cmds:
    - task: _rundeps
  dryrun_component_external_dns:
    cmds:
    - bin/deployer validate prod2 external_dns
    - bin/deployer dry-run prod2 external_dns
    desc: Dry-run deployment external_dns for prod2
    dir: $KR8_BASE/
    status:
    - bin/deployer diff prod2 external_dns
  dryrun_component_nginx_ingress:
    cmds:
    - bin/deployer validate prod2 nginx_ingress
    - bin/deployer dry-run prod2 nginx_ingress
    desc: Dry-run deployment nginx_ingress for prod2
    dir: $KR8_BASE/
    status:
    - bin/deployer diff prod2 nginx_ingress
  dryrun_component_pharos:
    cmds:
    - bin/deployer validate prod2 pharos
    - bin/deployer dry-run prod2 pharos
    desc: Dry-run deployment pharos for prod2
    dir: $KR8_BASE/
    status:
    - bin/deployer diff prod2 pharos
  dryrun_component_sealed_secrets:
    cmds:
    - bin/deployer validate prod2 sealed_secrets
    - bin/deployer dry-run prod2 sealed_secrets
    desc: Dry-run deployment sealed_secrets for prod2
    dir: $KR8_BASE/
    status:
    - bin/deployer diff prod2 sealed_secrets
  generate:
    cmds:
    - kr8-helpers check-environment
    - rm -fr $KR8_BASE/generated/prod2
    - task: _gendeps
  generate_component_external_dns:
    cmds:
    - KR8_CLUSTER=prod2 task generate KR8_COMPONENT=external_dns
    desc: Generate external_dns for prod2
    dir: $KR8_BASE/components/external_dns
  generate_component_nginx_ingress:
    cmds:
    - KR8_CLUSTER=prod2 task generate KR8_COMPONENT=nginx_ingress
    desc: Generate nginx_ingress for prod2
    dir: $KR8_BASE/components/nginx_ingress
  generate_component_pharos:
    cmds:
    - KR8_CLUSTER=prod2 task generate KR8_COMPONENT=pharos
    desc: Generate pharos for prod2
    dir: $KR8_BASE/components/pharos
  generate_component_sealed_secrets:
    cmds:
    - KR8_CLUSTER=prod2 task generate KR8_COMPONENT=sealed_secrets
    desc: Generate sealed_secrets for prod2
    dir: $KR8_BASE/components/sealed_secrets
version: "2"

