output: group
tasks:
  _deploydeps:
    deps:
    - deploy_component_nginx_ingress
    - deploy_component_sealed_secrets
  _gendeps:
    deps:
    - generate_component_nginx_ingress
    - generate_component_sealed_secrets
  _rundeps:
    deps:
    - dryrun_component_nginx_ingress
    - dryrun_component_sealed_secrets
  deploy:
    cmds:
    - task: _deploydeps
  deploy_component_nginx_ingress:
    cmds:
    - bin/deployer validate prod1 nginx_ingress
    - bin/deployer update prod1 nginx_ingress
    desc: deploy  nginx_ingress for prod1
    dir: $KR8_BASE/
    status:
    - bin/deployer diff prod1 nginx_ingress
  deploy_component_sealed_secrets:
    cmds:
    - bin/deployer validate prod1 sealed_secrets
    - bin/deployer update prod1 sealed_secrets
    desc: deploy  sealed_secrets for prod1
    dir: $KR8_BASE/
    status:
    - bin/deployer diff prod1 sealed_secrets
  dryrun:
    cmds:
    - task: _rundeps
  dryrun_component_nginx_ingress:
    cmds:
    - bin/deployer validate prod1 nginx_ingress
    - bin/deployer dry-run prod1 nginx_ingress
    desc: Dry-run deployment nginx_ingress for prod1
    dir: $KR8_BASE/
    status:
    - bin/deployer diff prod1 nginx_ingress
  dryrun_component_sealed_secrets:
    cmds:
    - bin/deployer validate prod1 sealed_secrets
    - bin/deployer dry-run prod1 sealed_secrets
    desc: Dry-run deployment sealed_secrets for prod1
    dir: $KR8_BASE/
    status:
    - bin/deployer diff prod1 sealed_secrets
  generate:
    cmds:
    - kr8-helpers check-environment
    - rm -fr $KR8_BASE/generated/prod1
    - task: _gendeps
  generate_component_nginx_ingress:
    cmds:
    - KR8_CLUSTER=prod1 task generate KR8_COMPONENT=nginx_ingress
    desc: Generate nginx_ingress for prod1
    dir: $KR8_BASE/components/nginx_ingress
  generate_component_sealed_secrets:
    cmds:
    - KR8_CLUSTER=prod1 task generate KR8_COMPONENT=sealed_secrets
    desc: Generate sealed_secrets for prod1
    dir: $KR8_BASE/components/sealed_secrets
version: "2"

