---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: clustergittrackobjects.faros.pusher.com
spec:
  group: faros.pusher.com
  names:
    kind: ClusterGitTrackObject
    plural: clustergittrackobjects
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            data:
              format: byte
              type: string
            kind:
              type: string
            name:
              type: string
          required:
          - name
          - kind
          - data
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  lastUpdateTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
          type: object
      type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: gittracks.faros.pusher.com
spec:
  group: faros.pusher.com
  names:
    kind: GitTrack
    plural: gittracks
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            deployKey:
              properties:
                key:
                  type: string
                secretName:
                  type: string
              required:
              - secretName
              - key
              type: object
            reference:
              type: string
            repository:
              type: string
            subPath:
              pattern: ^[a-zA-Z0-9/\-.]*$
              type: string
          required:
          - reference
          - repository
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  lastUpdateTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            objectsApplied:
              format: int64
              type: integer
            objectsDiscovered:
              format: int64
              type: integer
            objectsIgnored:
              format: int64
              type: integer
            objectsInSync:
              format: int64
              type: integer
          required:
          - objectsDiscovered
          - objectsApplied
          - objectsIgnored
          - objectsInSync
          type: object
      type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: gittrackobjects.faros.pusher.com
spec:
  group: faros.pusher.com
  names:
    kind: GitTrackObject
    plural: gittrackobjects
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            data:
              format: byte
              type: string
            kind:
              type: string
            name:
              type: string
          required:
          - name
          - kind
          - data
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  lastUpdateTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
          type: object
      type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []

